apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- frontend-deployment.yaml
- frontend-service.yaml
- redis-master-deployment.yaml
- redis-master-service.yaml
- redis-slave-deployment.yaml
- redis-slave-service.yaml

images:
- name: 918729401437.dkr.ecr.ap-southeast-2.amazonaws.com/guestbook
  newTag: latest
- name: 918729401437.dkr.ecr.ap-southeast-2.amazonaws.com/guestbook
  newTag: 7b806fbfe2b9ac943d781a36838b01d5f1e821b2
- name: frontend
  newName: guestbook
  newTag: 7b806fbfe2b9ac943d781a36838b01d5f1e821b2
- name: guestbook
  newName: guestbook
  newTag: new
